http:
  middlewares:
    auth:
      forwardAuth:
        address: "http://auth:4181" # Make sure you have the OAuth service in docker-compose.yml
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Forwarded-User"

    ratelimit:
      ratelimit:
        average: 100
        burst: 50
        
    ipWhiteList:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/16"
          - "192.168.0.0/16"
          - "172.16.1.0/24"

    deafultHeaders:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

  routers:
    proxmox:
      entrypoints:
        - "https"
      rule: "Host(`proxmox.nyx.scottmckendry.tech`)"
      middlewares:
        - ratelimit
        - ipWhiteList
        - auth
        - deafultHeaders
      tls: {}
      service: proxmox
    homeassistant:
      entrypoints:
        - "https"
      rule: "Host(`ha.nyx.scottmckendry.tech`)"
      middlewares:
        - ratelimit
        - ipWhiteList
        - deafultHeaders
      tls: {}
      service: homeassistant
  services:
    proxmox:
      loadBalancer:
        servers:
          - url: "https://10.0.20.1:8006"
    homeassistant:
      loadBalancer:
        servers:
          - url: "http://10.0.30.2:8123"
tcp:
  middlewares:
    ipWhiteList:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/16"
          - "192.168.0.0/16"
          - "172.16.1.0/24"

  routers:
    axis-forward-https:
      entrypoints:
        - "https"
      middlewares:
        - ipWhiteList
      rule: HostSNIRegexp(`^.+\.axis\.scottmckendry\.tech$`)
      tls:
        passthrough: true
      service: axis-forward-https
    axis-forward-http:
      entrypoints:
        - "http"
      middlewares:
        - ipWhiteList
      rule: HostSNIRegexp(`^.+\.axis\.scottmckendry\.tech$`)
      service: axis-forward-http
      tls:
        passthrough: true
  services:
    axis-forward-https:
      loadBalancer:
        servers:
          - address: "10.0.10.1:443"
    axis-forward-http:
      loadBalancer:
        servers:
          - address: "10.0.10.1:80"
